# Generated by Django 4.0 on 2022-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bachelor', '0002_availability_description_discount_enactus_jobstudent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('file', models.FileField(blank=True, upload_to='file')),
            ],
            options={
                'verbose_name': 'Каталог Университета МУИТ',
                'verbose_name_plural': 'Каталог Университета МУИТ',
            },
        ),
    ]
