# Generated by Django 4.0 on 2022-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0002_headerdis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('number', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
