# Generated by Django 4.0 on 2022-01-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0004_remove_sendmessage_date_remove_sendmessage_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sendmessage',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
