# Generated by Django 4.0 on 2022-01-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0006_category_quizzes_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='SendMessage',
        ),
    ]
