# Generated by Django 4.0 on 2022-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0008_job_fair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception_campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
