# Generated by Django 4.0 on 2022-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0009_reception_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms_of_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
