# Generated by Django 4.0 on 2022-01-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0010_forms_of_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturient.forms_of_training')),
            ],
        ),
    ]
