# Generated by Django 4.0 on 2022-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0011_description_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Карьера', 'verbose_name_plural': 'Карьера'},
        ),
        migrations.AlterModelOptions(
            name='description_form',
            options={'verbose_name': 'Описание формы обучения', 'verbose_name_plural': 'Описание формы обучения'},
        ),
        migrations.AlterModelOptions(
            name='forms_of_training',
            options={'verbose_name': 'Формы обучения', 'verbose_name_plural': 'Формы обучения'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterModelOptions(
            name='job_fair',
            options={'verbose_name': 'Ярмарка вакансий', 'verbose_name_plural': 'Ярмарка вакансий'},
        ),
        migrations.AlterModelOptions(
            name='reception_campaign',
            options={'verbose_name': 'Приемная', 'verbose_name_plural': 'Приемная'},
        ),
        migrations.AlterField(
            model_name='forms_of_training',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
