# Generated by Django 4.0 on 2022-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0013_open_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='upload_to')),
            ],
            options={
                'verbose_name': 'Новостной блог',
                'verbose_name_plural': 'Новостной блог',
            },
        ),
    ]
