# Generated by Django 4.0 on 2022-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0014_news_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='news_blog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
