# Generated by Django 4.0 on 2022-02-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0015_connect_alter_news_blog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.AlterModelOptions(
            name='connect',
            options={'verbose_name': 'Связь', 'verbose_name_plural': 'Связь'},
        ),
    ]
