# Generated by Django 4.0 on 2022-02-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0016_file_alter_connect_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadDis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturient.header')),
            ],
            options={
                'verbose_name': 'Описание Главной страницы',
                'verbose_name_plural': 'Описание Главной страницы',
            },
        ),
    ]
